spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8081

company:
  name: Alpha Ecommerce
  email: support@alpha.com
  phone: 9999999999

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/